Nodejs week3
oyelajakenny/meal-sharing pull request #3
Opened 2024-10-03 12:05 UTC by oyelajakenny

Meal sharing endpoints
Added more parameters to the meal route
Created the meal endpoint and implemented all routes and parameters

2024-10-05 13:33 UTC, kralle333 requested changes
Great work! Overall your code is very solid.

There are some small problems here and there I would like you to fix.

Keep it up!

2024-10-05 13:33 UTC, kralle333 commented on api/src/routers/meals.js
> +    await knex("Meal").insert(data);
I assume its `"meal"` instead of `"Meal"` :)

2024-10-05 13:33 UTC, kralle333 commented on api/src/routers/meals.js
> +      success: true,
getting an error code 200 should be good enough, no need to send an additional boolean here.

2024-10-05 13:33 UTC, kralle333 commented on api/src/routers/meals.js
> +    if (!id) {
I guess we can check this before querying the database :)

2024-10-05 13:33 UTC, kralle333 commented on api/src/routers/meals.js
> +      res.status(404).json({ error: "No meal with this ID found" });
are there no meals with this id, or is the request simply invalid? Tip: use the value returned from the delete statement to return the proper response.

2024-10-05 13:33 UTC, kralle333 commented on api/src/routers/reservations.js
> +    console.log(req.body);
I guess useful during testing, but for now we don't need this logging :)

2024-10-05 13:33 UTC, kralle333 commented on api/src/routers/reservations.js
> +    res.status(200).json({ message: "deleted successfully" });
what if there is no reservation with that id? Similar solution you can use in the meals routes

2024-10-05 13:33 UTC, kralle333 commented on api/src/routers/reviews.js
> +    res.status(505).json({ error: "Internal server error" });
500 should suffice in this situation, bonus if you remove the console.log ;)

2024-10-05 13:33 UTC, kralle333 commented on api/src/routers/reviews.js
> +      res.status(404).json({ error: "No review found" });
Here the proper response is actually 200! Weird right, but 404 is reserved for cases where the user expected some specific id to exist but didnt. Here the users asks for all the reviews for a specific meal and gets 0 if there are none, so it works as expected.

2024-10-05 13:33 UTC, kralle333 commented on api/src/routers/reviews.js
> +    res.status(505).json({ error: "Internal server error" });
500 here too ;)

2024-10-05 13:33 UTC, kralle333 commented on api/src/routers/reviews.js
> +    await knex("review").where({ id }).del();
same comment as in the other delete routes

2024-10-05 14:06 UTC, kralle333 commented on api/src/routers/meals.js
> +mealsRouter.get("/", async (req, res) => {
I believe you are missing one of the tasks here?
![image](https://github.com/user-attachments/assets/221114a6-9d6d-4508-91ee-8ee1d53bf394)

2024-10-05 15:20 UTC, kralle333 commented on api/src/routers/meals.js
> +    const data = req.body;
missing validation of the request here

2024-10-05 15:21 UTC, kralle333 commented on api/src/routers/reservations.js
> +    const data = req.body;
missing validation of the request here

2024-10-05 15:21 UTC, kralle333 commented on api/src/routers/reviews.js
> +    const data = req.body;
missing validation of the request here

2024-10-05 15:21 UTC, kralle333 commented on api/src/routers/reviews.js
> +    const data = req.body;
missing validation of the request here

2024-10-07 20:17 UTC, oyelajakenny commented on api/src/routers/meals.js
> +mealsRouter.get("/", async (req, res) => {
Hi @kralle333, I attempted all tasks, I have now added comments to distinguish them.

2024-11-06 13:37 UTC, oyelajakenny commented
Hi @kralle333 , apologies for the late feedback. I have now implemented all recommendations

2024-11-28 20:07 UTC, merged